### ISSUE TITLE
HSM Key Replacement

### ISSUE THREAD

**Issue by kategray** [cypresssemiconductorco/cysecuretools#1]
**Have you looked for an answer?**

I have looked for answers in the CY8CPROTO BSP, source code, google searches, and the forum.

**Question/Issue**:

Is it possible to do a custom HSM implementation for ROT provisioning?

Looking at hsm_state.json and through the implementation, it looks like there might be a static key.  I was able to find [this](https://www.cypress.com/file/480976/download) and [this](https://static4.arrow.com/-/media/arrow/files/pdf/psoc-64-arrow-iot-security-virtual-workshop-development-kit_-prework-guide-version-1-6-3.pdf?la=en&hash=BA6B6A967EEBFA85C3008B5B87CFDD811F8A2C3E) which refer to the process, but the information seemed a bit conflicting.

The Arrow document described the provisioning packet thusly:

```
Second: Create a Provisioning Packet:
• Use provided development cy_auth token 
• Use the provided OEM RoT key to sign keys and device policies
• Sign provisioning packet with HSM private key 
```

When reading the high level view it looks like it would involve the OEM RoT being given over to Arrow, who would then do the provisioning on the customer behalf.  The diagram would be consistent with a static HSM key, and perhaps even a specific HSM being required (for example, Thales with their SEE engine).  OEMs would then be dependent on that specific hardware, required to have that specific HSM.  Additionally, if an OEM could not qualify to have that HSM (for trust reasons, perhaps), they would need to work with a partner that did.

I am wondering if that's correct, or if the HSM key is something that depends on something like an X509 certificate, chained to the Cypress RoT.

The JWT objects later on make it seem like there should be multiple HSM keys, with the public keys being sent to both the OEM and Cypress for verification.  If that's the case, it seems odd that cysecure tools doesn't seem to have a mechanism to include that information without overwriting what looks like a static key.

**Context**

I make a smart-card based HSM, designed for key derivation and overbuilding prevention.  It's intended to be a cheap, easy, affordable way to manage distributed production, and functions similarly to what's described in the "secure facility" in your diagram.

At present, we are doing key derivation for CMAC keys, GlobalPlatform Keys, feature keys (feature unlocks), and a few other things.  Additionally, I sell devices based around the PSoC 5LP, and have written secure bootloader functionality around CMAC and the dongle, with the firmware requiring a license and keys generated through the dongle.  

I am considering moving future production over to the PSoC 6 on the next respin, and it would be nice to be able to support secure provisioning, as well as to have a solution I can offer for companies looking to adopt PSoC 6 that don't have a secure production facility.

A single, static, universal HSM key would make that more difficult, though it would likely still be possible to extend the OEM key management to use a PKCS11 interface in cysecuretools, then add key operation limits to that PKCS11 interface as a workaround.

**Where did you expect to find the answer?**

**Comment by rmbk19** [comment]
Hi @kategray, 

The static HSM key that is bundled with the cysecuretools is for the prototyping method of provisioning the PSoC 64 devices. For production procedure, Arrow, who is our exclusive partner for provisioning and the HSM for PSoC 64 devices should be able to help you with it.

Regards, 
Rakshith

**Comment by kategray** [comment]
That makes sense, thank you.
